#!/bin/sh

. $XDG_CONFIG_HOME/river/riverctl.lib

background-color 0x000000
border-width 3
border-color-focused 0x565E65
border-color-unfocused 0x393F45
border-color-urgent 0xC795AE

dbus-update-activation-environment --systemd \
    WAYLAND_DISPLAY \
    XDG_CURRENT_DESKTOP=river

# autostart
dex -a&
kanshi&
wlsunset \
    -l 52.2 \
    -L 8.5 \
    -t 3000 \
    -T 5300 &
rivertile \
    -view-padding 14 \
    -outer-padding 14 &
fnott&

keyboard-layout \
    -variant intl, \
    -options "grp:alt_space_toggle" \
    us,us

# defaults
mod='Super'
term='foot'
menu='fuzzel'

map normal $mod T spawn "$term"
map normal $mod R spawn "$menu"
map normal $mod C close
map normal $mod+Shift C exit
map normal $mod S spawn 'slurp -o | grim -g -'
map normal $mod+Shift S spawn 'slurp | grim -g -'
map normal $mod B spawn 'pkill yambar || yambar'
map normal $mod J focus-view next
map normal $mod K focus-view previous
map normal $mod+Shift J swap next
map normal $mod+Shift K swap previous
map normal $mod Period focus-output next
map normal $mod Comma focus-output previous
map normal $mod+Shift Period send-to-output next
map normal $mod+Shift Comma send-to-output previous
map normal $mod Return zoom
map normal $mod Space toggle-float
map normal $mod F toggle-fullscreen
map normal $mod+Alt Left move left 100
map normal $mod+Alt Down move down 100
map normal $mod+Alt Up move up 100
map normal $mod+Alt Right move right 100
map normal $mod+Alt+Control Left snap left
map normal $mod+Alt+Control Down snap down
map normal $mod+Alt+Control Up snap up
map normal $mod+Alt+Control Right snap right
map normal $mod+Alt+Shift Left resize horizontal -100
map normal $mod+Alt+Shift Down resize vertical 100
map normal $mod+Alt+Shift Up resize vertical -100
map normal $mod+Alt+Shift Right resize horizontal 100
map-pointer normal $mod BTN_LEFT move-view
map-pointer normal $mod BTN_RIGHT resize-view
map-pointer normal $mod BTN_MIDDLE toggle-float

for i in `seq 1 9`; do
    tags="$((1 << ($i - 1)))"

    map normal $mod $i set-focused-tags $tags
    map normal $mod+Shift $i set-view-tags $tags
    map normal $mod+Control $i toggle-focused-tags $tags
    map normal $mod+Shift+Control $i toggle-view-tags $tags
done

all_tags="$(((1 << 32) - 1))"
map normal $mod 0 set-focused-tags $all_tags
map normal $mod+Shift 0 set-view-tags $all_tags

for mode in normal locked; do
    map $mode None XF86Eject spawn 'eject -T'
    map $mode None XF86AudioRaiseVolume spawn 'wpctl set-volume -l 1.5 @DEFAULT_AUDIO_SINK@ 5%+'
    map $mode None XF86AudioLowerVolume spawn 'wpctl set-volume @DEFAULT_AUDIO_SINK@ 5%-'
    map $mode None XF86AudioMute spawn 'wpctl set-mute @DEFAULT_AUDIO_SINK@ toggle'
    map $mode None XF86AudioMicMute spawn 'wpctl set-mute @DEFAULT_AUDIO_SOURCE@ toggle'
    map $mode None XF86AudioMedia spawn 'playerctl play-pause'
    map $mode None XF86AudioPlay spawn 'playerctl play-pause'
    map $mode None XF86AudioPrev spawn 'playerctl previous'
    map $mode None XF86AudioNext spawn 'playerctl next'
    map $mode None XF86MonBrightnessUp spawn 'brightnessctl set +5%'
    map $mode None XF86MonBrightnessDown spawn 'brightnessctl set 5%-'
done

set-repeat 70 220

default-layout rivertile
default-attach-mode bottom

hide-cursor timeout 3000
hide-cursor when-typing enabled

for input in `list-inputs | grep 'pointer'`; do
    input "$input" accel-profile flat
done

rule-add -app-id '*' ssd

rule-add -app-id '*.exe' float
rule-add -app-id '*.exe' csd
rule-add -app-id '*.exe' tearing

rule-add -app-id 'steam_app_*' tags "$((1 << (9 - 1)))"
rule-add -app-id 'steam_app_*' float
rule-add -app-id 'steam_app_*' csd
rule-add -app-id 'steam_app_*' tearing
