#!/bin/sh

dbus-update-activation-environment --systemd \
	WAYLAND_DISPLAY \
	XDG_CURRENT_DESKTOP=river

dex -a&
kanshi&
wlsunset -l 52.2 -L 8.5&
rivertile -view-padding 33 -outer-padding 33&
yambar&

mod='Super'
term='foot'
menu='fuzzel'

alias nmap='riverctl map normal'
alias ptrnmap='riverctl map-pointer normal'
alias map='riverctl map'
alias rulea='riverctl rule-add'

nmap $mod T spawn "$term"
nmap $mod R spawn "$menu"
nmap $mod C close
nmap $mod+Shift C exit
nmap $mod S spawn 'slurp -o | grim -g -'
nmap $mod+Shift S spawn 'slurp | grim -g -'
nmap $mod B spawn 'pkill yambar || yambar'
nmap $mod J focus-view next
nmap $mod K focus-view previous
nmap $mod+Shift J swap next
nmap $mod+Shift K swap previous
nmap $mod Period focus-output next
nmap $mod Comma focus-output previous
nmap $mod+Shift Period send-to-output next
nmap $mod+Shift Comma send-to-output previous
nmap $mod Return zoom
nmap $mod Space toggle-float
nmap $mod F toggle-fullscreen
nmap $mod+Alt Left move left 100
nmap $mod+Alt Down move down 100
nmap $mod+Alt Up move up 100
nmap $mod+Alt Right move right 100
nmap $mod+Alt+Control Left snap left
nmap $mod+Alt+Control Down snap down
nmap $mod+Alt+Control Up snap up
nmap $mod+Alt+Control Right snap right
nmap $mod+Alt+Shift Left resize horizontal -100
nmap $mod+Alt+Shift Down resize vertical 100
nmap $mod+Alt+Shift Up resize vertical -100
nmap $mod+Alt+Shift Right resize horizontal 100
ptrnmap $mod BTN_LEFT move-view
ptrnmap $mod BTN_RIGHT resize-view
ptrnmap $mod BTN_MIDDLE toggle-float

for i in `seq 1 9`; do
    tags=$((1 << ($i - 1)))

    nmap $mod $i set-focused-tags $tags
    nmap $mod+Shift $i set-view-tags $tags
    nmap $mod+Control $i toggle-focused-tags $tags
    nmap $mod+Shift+Control $i toggle-view-tags $tags
done

all_tags=$(((1 << 32) - 1))
nmap $mod 0 set-focused-tags $all_tags
nmap $mod+Shift 0 set-view-tags $all_tags

for mode in normal locked; do
    map $mode None XF86Eject spawn 'eject -T'
    map $mode None XF86AudioRaiseVolume spawn 'wpctl set-volume -l 1.5 @DEFAULT_AUDIO_SINK@ 5%+'
    map $mode None XF86AudioLowerVolume spawn 'wpctl set-volume @DEFAULT_AUDIO_SINK@ 5%-'
    map $mode None XF86AudioMute spawn 'wpctl set-mute @DEFAULT_AUDIO_SINK@ toggle'
    map $mode None XF86AudioMicMute spawn 'wpctl set-mute @DEFAULT_AUDIO_SOURCE@ toggle'
    map $mode None XF86AudioMedia spawn 'playerctl play-pause'
    map $mode None XF86AudioPlay spawn 'playerctl play-pause'
    map $mode None XF86AudioPrev spawn 'playerctl previous'
    map $mode None XF86AudioNext spawn 'playerctl next'
    map $mode None XF86MonBrightnessUp spawn 'brightnessctl set +5%'
    map $mode None XF86MonBrightnessDown spawn 'brightnessctl set 5%-'
done

riverctl background-color 0xc9c5cb
riverctl border-width 0

riverctl set-repeat 70 220

riverctl default-layout rivertile

riverctl hide-cursor timeout 3000
riverctl hide-cursor when-typing enabled

riverctl default-attach-mode bottom

riverctl input "pointer-12815-8794-Nordic_Semiconductor_USB__Gaming_Mouse" accel-profile flat

rulea -app-id 'steam_app_*' tags $((1 << (9 - 1)))
rulea -app-id 'steam_app_*' float
rulea -app-id 'steam_app_*' csd
rulea -app-id 'steam_app_*' tearing

rulea -app-id 'org.mozilla.firefox' ssd
rulea -app-id 'steam' ssd

for input in `riverctl list-inputs | grep 'pointer'`; do
    riverctl input $input accel-profile flat
done

riverctl keyboard-layout -variant intl us
setxkbmap us // only works until Proton supports Wayland
