bar:
  height: 64
  location: top
  foreground: 252323ff
  background: d7d9d7ff
  font: Cousine:size=18

  center:
    - clock:
        time-format: "%H:%M:%S"
        date-format: "%d/%m/%Y"
        content:
          string: {text: "{time} {date}"}
